services:
  #nginx
  nginx:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "81:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #php
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - /app/vendor # the folder is not overwritten
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    extra_hosts:
      - host.docker.internal:host-gateway # for xdebug